version: '3.7'

services:
  server:
    container_name: nestjs_server
    image: nestjs/server:1.0
    build:
      context: ./server
      dockerfile: ./dockerfile
    working_dir: /home/node/app
    restart: always
    depends_on:
      - db
    ports:
      - 3005:3005
    volumes:
      - ./server:/home/node/app
    command: "yarn run start:dev"
    networks:
      - postgres

  db:
    container_name: nestjs_db
    image: postgres
    restart: always
    volumes:
      - ./server_db:/var/lib/mysql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  server:
  db:
